* Egyptology with Emacs
** =translit.el=
   Provides an input method (i.e. a ‘keyboard’) for entering Unicode transliteration characters in Emacs.  For more on input methods in Emacs, see [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Input-Methods.html][the relevant section of the Emacs manual]].

   Your Emacs fonts must include the necessary Unicode characters for displaying Egyptian transliteration correctly.  Try [[https://fonts.google.com/noto][Noto Sans Mono]] for fixed pitch, and [[http://software.sil.org/charis/download/][Charis SIL]] or [[https://brill.com/page/290][Brill]] for variable pitch.  For more information, see https://jsesh.qenherkhopeshef.org/varia/transliteration.
*** Installation
    Copy =translit.el= to wherever you want to keep it.  In your init file, add that directory to your load-path (if you have not already done so), then load the transliteration scheme itself:

 #+begin_src 
 (add-to-list 'load-path "~/.emacs.d/elisp/") ; (or wherever you want to keep the script.)

 (load "translit.el") ; load the transliteration scheme itself.
 #+end_src

 To load the transliteration scheme immediately, execute each of these lines with =C-x C-e=.

*** Use
 To select a different input method (in this case transliteration): =C-u C-\= and then select =transliteration=.

 To cycle the transliteration keyboard on and off: =C-\= 
